# Generated by Django 4.1.6 on 2023-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fireman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
