# Generated by Django 4.1.6 on 2023-02-13 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='questions.tag')),
            ],
        ),
    ]
