# Generated by Django 4.1.6 on 2023-02-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='views',
            new_name='views_count',
        ),
    ]
