# Generated by Django 4.1.6 on 2023-02-13 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('is_favorite',
                 models.BooleanField(
                     default=False)),
                ('question',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='questions.question')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='favorites',
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
