# Generated by Django 4.1.6 on 2023-02-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackOverflowParser',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=255)),
                ('link',
                 models.CharField(
                     max_length=255)),
            ],
        ),
    ]
