# Generated by Django 4.1.6 on 2023-02-14 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReview',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('is_liked',
                 models.BooleanField(
                     default=False)),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comment_reviews',
                     to=settings.AUTH_USER_MODEL)),
                ('comment',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comment_reviews',
                     to='answers.comment')),
            ],
        ),
    ]
